### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by CarlosRubioTNM** [JoanLuna/404-Pagina-web-clase-front-end-#1]
Muy bien, jóvenes.

Les dejo unas correcciones para que realicen:
- Insertar el perfil de Paulina.
- Asegurarse de que todos los perfiles tengan por lo menos una imagen.
- Añadir un párrafo inventado sobre la historia de su empresa.

Por favor etiquétenme en este issue cuando terminen los cambios, para revisar y finalizar la práctica.

**Comment by JoanLuna** [comment]
@CarlosRubioTNM ya están hechos los cambios

**Comment by CarlosRubioTNM** [comment]
Muy bien, jóvenes. Al parecer hay un problemita, con el perfil de Paulina, pero agregaron lo que les pedí. Cierro el issue, Buen trabajo. 👍
